#Use Trusty
sudo: required
dist: trusty

#Install some apt packages needed for spcomp
addons:
    apt_packages:
        - lib32stdc++6

#Set the build environment
env:
    - SMVERSION=1.8

#And compile!
install:
    - wget http://sourcemod.net/smdrop/$SMVERSION/ -O - | grep "\.tar\.gz" | sed 's/^.*"sourcemod/sourcemod/;s/\.tar\.gz".*$/.tar.gz/' | tail --lines=1 > sourcemod
    - wget --input-file=sourcemod --base=http://sourcemod.net/smdrop/$SMVERSION/
    - tar -xzf $(cat sourcemod)
before_script:
    - cd addons/sourcemod/scripting/
    - wget "http://hg.limetech.org/projects/tf2items/tf2items_source/raw-file/tip/pawn/tf2items.inc" -O include/tf2items.inc
    - wget "http://www.doctormckay.com/download/scripting/include/morecolors.inc" -O include/morecolors.inc
    - wget "http://hg.limetech.org/projects/steamtools/raw-file/tip/plugin/steamtools.inc" -O include/steamtools.inc
    - wget "https://bitbucket.org/GoD_Tony/updater/raw/default/include/updater.inc" -O include/updater.inc
    - wget "https://forums.alliedmods.net/attachment.php?attachmentid=116849&d=1377667508" -O include/tf2attributes.inc
    - chmod +x spcomp
script: ./compile.sh tf2x10.sp

#Github Releases
deploy:
    provider: releases
    api_key:
        secure: e//ORGbgqcw95Ft9cB0pF21WLmk5gMVPiC5bczBkKUyBxhTaBnn0ZA6tdzewWt8KEiQ8FYTX26JKHDVBzet7YVLe4frg0DvQu9H65IBe3lOUL+PsgEH/FOyC6fP0AYts418LPZNRcsWrStrTrALw3bTvAI/zDQbqPT/sQgQjpWU=
    file:
        - compiled/tf2x10.smx
        - ../configs/x10.default.txt
        - tf2x10.sp
    skip_cleanup: true
    on:
        repo: 50DKP/TF2x10
        tags: true

notifications:
    email: false